---
services:
    openvpn:
       container_name: openvpn
       # If you want to build your own image with docker-compose, uncomment the next line, comment the "image:" line and run "docker-compose build" following by "docker-compose up -d"
       # build: .
       image: local/openvpn-server:latest
       privileged: true
       ports:
          - "1194:1194/udp"   # openvpn UDP port
         # - "1194:1194/tcp"   # openvpn TCP port
         # - "2080:2080/tcp"  # management port. uncomment if you would like to share it with the host
       volumes:
           - ./pki:/etc/openvpn/pki
           - ./clients:/etc/openvpn/clients
           - ./config:/etc/openvpn/config
           - ./staticclients:/etc/openvpn/staticclients
           - ./log:/var/log/openvpn
           - ./fw-rules.sh:/opt/app/fw-rules.sh
           - ./checkpsw.sh:/opt/app/checkpsw.sh
           - ./server.conf:/etc/openvpn/server.conf
       cap_add:
           - NET_ADMIN
       restart: unless-stopped
       depends_on:
           - "openvpn-ui"

    openvpn-ui:
       container_name: openvpn-ui
       image: local/openvpn-ui:latest
       env_file: ".env"
       environment:
           - OPENVPN_ADMIN_USERNAME=${OPENVPN_ADMIN_USERNAME}
           - OPENVPN_ADMIN_PASSWORD=${OPENVPN_ADMIN_PASSWORD}
       privileged: true
       volumes:
           - ./:/etc/openvpn
           - ./db:/opt/openvpn-ui/db
           - ./pki:/usr/share/easy-rsa/pki
           - /var/run/docker.sock:/var/run/docker.sock:ro
       restart: unless-stopped

    caddy:
      container_name: caddy
      image: caddy:latest
      env_file: ".env"
      environment:
        - WEB_DOMAIN=${WEB_DOMAIN}
      restart: unless-stopped
      # Use :80 or :8080 to disable SSL, otherwise use real domain
      command: caddy reverse-proxy --from "$WEB_DOMAIN" --to openvpn-ui:8080
      ports:
        - "443:443"
        - "80:80"
      volumes:
        - ./caddy/data:/data
